### ISSUE TITLE
Update to support tree-sitter 0.19.3

### ISSUE THREAD

**Issue by tami5** [cstrahan/tree-sitter-nix#10]
Hey @cstrahan, hope you doing great. I was trying to use tree-sitter-nix but didn't work, I think its due to version miss-match. It would be awesome if it gets update. Thanks

**Comment by 06kellyjac** [comment]
Yeah the need for an update to tree-sitter-nix is also mentioned here: https://github.com/nvim-treesitter/nvim-treesitter/issues/994#issuecomment-805213716
