### ISSUE TITLE
$${variable} escapes still highlight as interpolation

### ISSUE THREAD

**Issue by nagisa** [cstrahan/tree-sitter-nix#15]
In nix `$${...}` escapes the interpolation and includes into string `${...}` verbatim, rather than trying to evaluate the expression within the curly braces.

However (at least in nvim) this is highlit as the first `$` being a string content and following `${...}` as the regular interpolation.

**Comment by chuahou** [comment]
I've just tried out tree-sitter-nix in conjunction with nvim-treesitter to decide whether to use it to replace vim-nix, but found that it did not provide highlighting for string interpolation (i.e. an expression like `"something/${some.nix.here}"` had the entire string still highlighted as a string literal.

Are dollar-curly expressions highlighted differently from you using this?

(I've only started trying nvim-treesitter today so it's possible I'm not configuring anything properly, so take this with a handful of salt.)

**Comment by cstrahan** [comment]
Ah, I wasn't aware of this; sure enough:

```
nix-repl> b = "b"           

nix-repl> "a${b}c"
"abc"

nix-repl> "a$${b}c"
"a$${b}c"

nix-repl> "a$$${b}c"
"a$$bc"

nix-repl> ''a${b}c''
"abc"

nix-repl> ''a$${b}c''
"a$${b}c"

nix-repl> ''a$$${b}c''
"a$$bc"

```

I'll get to this a little later today. Should be an easy fix in `scanner.c`.

Thanks for bringing this to my attention!

**Comment by nagisa** [comment]
@chuahou this is not exactly the right place for support, but yes, I do have useful highlighting with treesitter. My only guess is that you haven't set up treesitter correctly. It is not super trivial to do if you want to do so in Nix-land.

**Comment by cstrahan** [comment]
I see, these are the two parts I've messed up:

* the `\$[^\{\"\\]` pattern in https://github.com/NixOS/nix/blob/1af3f63be53018ab764090acab36e7c5401609cd/src/libexpr/lexer.l#L161
* the `\$[^\{\']` pattern in https://github.com/NixOS/nix/blob/1af3f63be53018ab764090acab36e7c5401609cd/src/libexpr/lexer.l#L179

**Comment by chuahou** [comment]
@nagisa Yeah, I know, I wasn't asking for support, sorry if it came off that way. I simply thought that string interpolation highlighting wasn't supported by tree-sitter-nix, and wanted to check (in the context of the issue) that the interpolation highlighting you talked about was indeed due to tree-sitter-nix.

**Comment by cstrahan** [comment]
@nagisa Should be fixed now. Let me know if you spot anything else!
