### ISSUE TITLE
Doesn't highlight in NeoVim with `indent.enable = true` setting

### ISSUE THREAD

**Issue by SenchoPens** [cstrahan/tree-sitter-nix#17]
Hi, first of all great thanks to you for your work!
With the following configuration treesitter doesn't highlight `.nix` files:
```
require('nvim-treesitter.configs').setup {
  ensure_installed = {"python", "go", "cpp", "nix", "yaml", "bash"}, -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },

  indent = {
    enable = true
  },
}
```

I know that tree-sitter-nix doesn't support indent, but tree-sitter-bash doesn't support it too, but `.sh` files do get highlighted. If i disable `indent`, everything works. I'm using the latest version of `tree-sitter-nix`.

**Comment by cstrahan** [comment]
@oxalica might be able to help -- I haven't set up `tree-sitter-nix` with neovim yet (though I would like to).

**Comment by SenchoPens** [comment]
Hi! I've updated to NixOS 22.05 and it's working beautifully now! Thanks soo much for the plugin!

NeoVim v0.7.0
`nixpkgs#legacyPackages.x86_64-linux.tree-sitter-grammars.tree-sitter-nix` v0.20.6
`nixpkgs#legacyPackages.x86_64-linux.vimPlugins.nvim-treesitter` v2022-05-13
