### ISSUE TITLE
Bug with /**/ style comments

### ISSUE THREAD

**Issue by eviefp** [cstrahan/tree-sitter-nix#23]
So it looks like if the closing `*/`has a `*` right before, it will not parse correctly.

```nix
  /* blah */
  /* blah x*/
  /* blah /*/
  /* blah **/
```
First three work just fine, the last one does not.

![image](https://user-images.githubusercontent.com/1017953/151678501-da4bdcb9-c04a-4d80-9e16-ddc9629ea13c.png)

**Comment by cstrahan** [comment]
Thank you for the report -- should be fixed now :slightly_smiling_face:
