### ISSUE TITLE
__typeof__ isn't supported on Windows

### ISSUE THREAD

**Issue by Wilfred** [cstrahan/tree-sitter-nix#28]
As of 734a4ccaed0d3980d170acf66b0af48852ed5364, tree-sitter-nix no longer builds on Windows. Turns out that `__typeof__` is a GCC extension supported by clang, but not MSVC. Would you be willing to revert this change?

This is preventing difftastic building on Windows with the latest version of tree-sitter-nix.

**Comment by the-mikedavis** [comment]
Given that the `lookahead` field has its type [documented](https://github.com/tree-sitter/tree-sitter/blob/465ceead0faf3a0aab311806795664a2c2fad5de/docs/section-3-creating-parsers.md?plain=1#L673), I think it's reasonable to just use `int32_t`. What do you think @cstrahan?

**Comment by cstrahan** [comment]
> Given that the lookahead field has its type [documented](https://github.com/tree-sitter/tree-sitter/blob/465ceead0faf3a0aab311806795664a2c2fad5de/docs/section-3-creating-parsers.md?plain=1#L673), I think it's reasonable to just use `int32_t`.

Yep -- will do!

I remember looking at difftastic a couple weeks ago, and even thought about proposing Nix support -- I had no idea you already added that @Wilfred, nice!
