### ISSUE TITLE
`$` should be a part of string fragment on escape

### ISSUE THREAD

**Issue by nrdxp** [cstrahan/tree-sitter-nix#32]
During an escape, the `$` is consumed as parse of the `escape_sequence`, however if one were to run `nix eval --raw --expr '"\${foo}"'`, it would return the string `${foo}`. To make this clear, here is the concrete syntax tree generated by this grammar for the same nix expression:
```xml
<source_code>
  <string_expression type="expression">"
    <escape_sequence>\$</escape_sequence>

    <string_fragment>{foo}</string_fragment>
"</string_expression>
</source_code>
```

Technically the `$` char is both part of the escape, _and_ a part of the string, and I'm not sure if tree-sitter has a construct for such a situation. Although perhaps it can be worked out manually in the scanner.

This is an issue for [bash injection](https://github.com/cstrahan/tree-sitter-nix/pull/31), for example, where `{foo}` is interpreted as a shell block, when it should be read as the variable `${foo}`.

**Comment by cstrahan** [comment]
Ahhh. That's really interesting -- I hadn't thought of how emitting the `\$` as a single escape token would throw a wrench in language injection. Thanks for the report & PR!
