### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zimbatm** [cstrahan/tree-sitter-nix#6]
This project needs a license so it can be used by other projects.

If you go to https://github.com/cstrahan/tree-sitter-nix/new/master and type "LICENSE" as the file name, GitHub shows a license chooser menu.

**Comment by cstrahan** [comment]
Hey @zimbatm :). Sorry I missed this issue.

So, I have MIT specified in the `package.json`, but forgot to add a license file. I'll fix that up.

**Comment by zimbatm** [comment]
thanks :)
