### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by asymmetric** [cstrahan/tree-sitter-nix#7]
Hi! I've run the tests and the only failing one is the one for comments.

Is there anything blocking the completion of the corpus? I'd be happy to take a look at it, but would first like to know what the current status is.

**Comment by Profpatsch** [comment]
I’d love to have this working.

I recently added all existing official tree-sitter grammars to nixpkgs, so they are now usable from within nix: https://github.com/NixOS/nixpkgs/pull/107514

It would be amazing to have a working nix gramar as well.

**Comment by cstrahan** [comment]
Hey, sorry -- life has been crazy, and I don't have a good system in place yet to be prompt about new issues across my repos (need to clean up my email and play around a bit with GitHub configs, perhaps).

That said, I'm definitely interested in this being a go to parsing resource for the community.

I just pushed up some work, and I'll see if there's anything remaining to fix up. It should otherwise be in great shape.

If you get a chance to use it, I'd love feedback! I originally figured I'd use this for a nix source code formatter, but I haven't had the time to focus on that, and it looks like others have already made a couple competing tools in that space.

**Comment by cstrahan** [comment]
I put a lot of effort into getting everything right, so the grammar should be solid. If you can think of any more cases to add to the corpus, let me know (or feel free to submit a PR).

Just pushed a commit to fix the test and added a GitHub action for testing (will probably remove the Travis tests at some point).

**Comment by cstrahan** [comment]
I would also love some feedback on the ergonomics of the parse tree. Considerations like what was discussed here: https://github.com/cstrahan/tree-sitter-nix/pull/5

**Comment by cstrahan** [comment]
Do you have any thoughts on this issue? https://github.com/cstrahan/tree-sitter-nix/issues/2 /cc @justinwoo 

After coming back to this project for the first time in a long while, I might have changed my verdict there. I actually got a little confused myself when I was looking at a `let` token, vs the `let` node -- both have the same `type: "let"`. While part of me seems like it's a little redundant, I'm seriously considering adding `_expr` to the end of each expression node type. It's only a couple more characters, and it avoids the `let` token vs `let` node issues. It also puts us a little  more inline with the other grammars (where they usually have stuff like `if_expression`, etc).

Would be nice to make any improvements sooner than later, so the parse tree can stabilize.

**Comment by justinwoo** [comment]
I haven't been using any tree-sitter grammars due to issues I have with tree-sitter but overall I think it's better to be able to work with explicit nodes in general. I think in my previous use of this grammar I ended up mostly using my work which did disambiguate those and others.

**Comment by milahu** [comment]
> overall I think it's better to be able to work with explicit nodes

yepp! when editing sources, we need concrete syntax trees, aka "lossless" syntax trees ([rowan](https://crates.io/crates/rowan))

> I would also love some feedback on the ergonomics of the parse tree.

there is collision between the `if` block and the `if` keyword

```
if
  if
  x
  then
  x
  else
  x
```

rename the if block to `ifthenelse`?

rename `comment` to `commentblock` for `/* asdf */`?

rename `indented_string` to `stringblock`?

rename `source_expression` to `nixexpr`?

maybe only on incremental parsing:

* top-level comments give parse error
* empty input gives parse error


sample use: [syntax highlighting with tree-sitter in monaco-editor](https://github.com/milahu/monaco-tree-sitter)

in the screenshots, `if` is mapped to classname `control`
`number` should be white, but the `control` class has higher precedence
so the whoe `ifthenelse` block has the same color

<img src="https://user-images.githubusercontent.com/12958815/142030402-ae1177d9-690b-4849-8b48-37b508b2620c.png" width="486">

**Comment by asymmetric** [comment]
I’m going to close this, we can discuss further in more on-topic issues IMO.
